import type { CareerType } from "@lib/types";
import {
    siHtml5,
    siCss,
    siJavascript,
    siMysql,
    siCplusplus,
    siPhp,
    siDotnet,
    siKotlin,
    siSwift,
    siReact,
    siNodedotjs,
    siNextdotjs,
    siPostgresql,
    siTypescript,
    siTailwindcss
} from "simple-icons";

export const careerData: CareerType[] = [
    {
        category: "education",
        title: "Diploma in Information Technology",
        organization: "Tunku Abdul Rahman University College (TARC)",
        organizationUrl: "https://tarc.edu.my/",
        location: "Setapak, Kuala Lumpur, Malaysia",
        startDate: new Date(2020, 5),
        endDate: new Date(2022, 5),
        isCurrent: false,
        description: `Built a strong foundation in core software development concepts, mastering object-oriented programming and complex problem-solving with C++. Gained comprehensive exposure to the full software development lifecycle, from debugging to deployment, while designing systems involving web development, database management, and system architecture.`,
        learnedSkills: [
            { name: "HTML", icon: siHtml5.path, style: "text-orange-600" },
            { name: "CSS", icon: siCss.path, style: "text-blue-500" },
            { name: "JavaScript", icon: siJavascript.path, style: "text-yellow-400" },
            { name: "MySQL", icon: siMysql.path, style: "text-blue-600" },
            { name: "C++", icon: siCplusplus.path, style: "text-blue-700" },
        ],
    },
    {
        category: "internship",
        title: "Web Developer",
        organization: "Lakaran Cinta Sistem Empire",
        organizationUrl: "https://www.lakarancintasistem.com/",
        location: "Petaling Jaya, Shah Alam, Malaysia",
        startDate: new Date(2021, 10),
        endDate: new Date(2021, 12),
        isCurrent: false,
        description: `Engineered a responsive, customer-facing website for a local business utilizing HTML, CSS, and JavaScript. Focused on UI/UX best practices to improve site navigation and visual hierarchy, ensuring a seamless experience across mobile and desktop devices.`,
        learnedSkills: [
            { name: "HTML", icon: siHtml5.path, style: "text-orange-600" },
            { name: "CSS", icon: siCss.path, style: "text-blue-500" },
            { name: "JavaScript", icon: siJavascript.path, style: "text-yellow-400" },
        ],
    },
    {
        category: "education",
        title: "Bachelor of Information Technology (Honours) in Information Security",
        organization: "Tunku Abdul Rahman University of Management and Technology (TARUMT)",
        organizationUrl: "https://tarc.edu.my/",
        location: "Setapak, Kuala Lumpur, Malaysia",
        startDate: new Date(2022, 7),
        endDate: new Date(2024, 8),
        isCurrent: false,
        description: `Specialized in cybersecurity strategies to secure enterprise infrastructure. Mastered theoretical and practical applications of ethical hacking, cryptography, and penetration testing. Deepened knowledge in network security, risk assessment, and IT governance, preparing to tackle modern security threats in complex digital environments.`,
        learnedSkills: [
            { name: "PHP", icon: siPhp.path, style: "text-indigo-500" },
            { name: "ASP.NET", icon: siDotnet.path, style: "text-purple-600" },
            { name: "Kotlin", icon: siKotlin.path, style: "text-purple-500" },
        ],
    },
    {
        category: "internship",
        title: "Software Developer",
        organization: "Advanced Product Design Sdn. Bhd.",
        organizationUrl: "https://biocryptodisk.com/",
        location: "Skudai, Malaysia",
        startDate: new Date(2024, 2),
        endDate: new Date(2024, 8),
        isCurrent: false,
        description: `Contributed to the development of a secure video conferencing solution across web and desktop platforms. Engineered backend logic using PHP and enhanced native client performance for macOS and iOS using Swift. Collaborated within a cross-functional team to integrate secure data transmission features and optimize real-time communication.`,
        learnedSkills: [
            { name: "Swift", icon: siSwift.path, style: "text-orange-500" },
        ],
    },
    {
        category: "job",
        title: "Full-Stack Web Developer",
        organization: "Morning Geek",
        location: "Malaysia",
        startDate: new Date(2024, 9),
        isCurrent: true,
        description: `Architecting and developing scalable full-stack web applications while driving technical decision-making and system design using the Next.js ecosystem. Implementing robust backend solutions with Node.js and PostgreSQL while crafting high-performance, accessible frontends using React, TypeScript, and Tailwind CSS.`,
        learnedSkills: [
            { name: "React", icon: siReact.path, style: "text-cyan-400" },
            { name: "Node.js", icon: siNodedotjs.path, style: "text-green-600" },
            { name: "Next.js", icon: siNextdotjs.path, style: "text-black dark:text-white" },
            { name: "PostgreSQL", icon: siPostgresql.path, style: "text-blue-400" },
            { name: "TypeScript", icon: siTypescript.path, style: "text-blue-600" },
            { name: "Tailwind CSS", icon: siTailwindcss.path, style: "text-cyan-500" },
        ],
    },
];